### Recuperar informacion de peliculas
GET http://localhost:1234/movies
###Recuperar segun id
GET http://localhost:1234/movies/6869b901194c7a32f2d47c63

### Aca tenemos un filtro query string
GET http://localhost:1234/movies?genre=drama


### Para crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration":175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre":[
        "Drama"
    ]
}

###updateamos la primera pelicula
PATCH http://localhost:1234/movies/6869b963aeee07de7b8aa764
Content-Type: application/json

{
  "id": "6869b963aeee07de7b8aa764",
  "title": "The Godfather",
  "genre": ["Drama", "Action"]
}
####

DELETE http://localhost:1234/movies/6869bddc8d52a23472a8ef6c